### ISSUE TITLE
EZTupleBase 构造问题

### ISSUE THREAD

**Issue by YanweiLi** [meituan/EasyTuple#25]
+ (__kindof EZTupleBase *)tupleWithCount:(NSUInteger)count {
#define TUPLE_CLASS(_COUNT_)    "EZTuple" EZ_STRINGIFY(_COUNT_)
#define CLASS_TABLE             EZ_FOR_COMMA(20, TUPLE_CLASS)
    static const char *classNames[] = {
        CLASS_TABLE
    };
#undef CLASS_TABLE
#undef TUPLE_CLASS
    NSAssert(count <= 20 && count != 0, @"There is only 20 tuple classes.");
    const char *className = classNames[count];
    Class tupleClass = objc_getClass(className);
    EZTupleBase *tuple = [tupleClass new];
    return tuple;
}

如果count==20，会发生什么呢？   tupleClass = 0x0?

* EasyTuple version:EasyTuple-1.1.2

**Comment by ValiantCat** [comment]
只支持 20个长度  
实际上超过5个元素的元组  就应该给其抽象对应的数据结构

**Comment by WilliamZang** [comment]
在DEBUG环境下会Assert，在Release环境下会异常访问
